kind: pipeline
type: docker
name: pipelinedefaresthomas

  trigger:
    branch:
      include:
        - master
        - F3_Class
        - feat*
      exclude:
      - doc*
    event:
      - push

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - cd /Sources
      - dotnet restore solution.sln
      - dotnet build solution.sln -c Release --no-restore

  - name: test
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - cd /Sources
      - dotnet restore solution.sln
      - dotnet build solution.sln -c Release --no-restore

  - name: code_analysis
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - cd /Sources
      - dotnet restore solution.sln
      - dotnet build solution.sln -c Release --no-restore

  - name: doc
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - cd /Sources
      - dotnet restore solution.sln
      - dotnet build solution.sln -c Release --no-restore